### ISSUE TITLE
Can I submit Premium Hugo themes 

### ISSUE THREAD

**Issue by mehedi-sharif** [stackbithq/jamstackthemes#107]
Hello Team ,
I am the founder of gethugothemes.com . We have almost 40+ hugo themes in our directory . Most of them premium . Is there any way to put our premium themes in your website ? 
And thanks for creating such a great directory .
Thanks

**Comment by JugglerX** [comment]
@mehedi-sharif Hi Mehedi, we don't support premium themes at the moment. Perhaps in the future. You are welcome to add or update any of your free themes.

**Comment by mehedi-sharif** [comment]
@JugglerX 
Thank you so much for the prompt reply. Yeah we have a plan to add our free templates soon 
Thanks
