### ISSUE TITLE
Add Strapi cms

### ISSUE THREAD

**Issue by collinsmuriuki** [stackbithq/jamstackthemes#137]
Noticed [Strapi](https://strapi.io) is not included in the cms list. Would be great to have it there since I have a theme using it that I'd like to submit.

**Comment by JugglerX** [comment]
Hi @collinsmuriuki - Strapi should be on the list for sure! We just havent had any themes submitted that use it yet.

You can add Strapi as a CMS as part of your PR - instructions are in the README.

**Comment by collinsmuriuki** [comment]
Cool, will do that
