### ISSUE TITLE
Update site

### ISSUE THREAD

**Issue by uPagge** [stackbithq/jamstackthemes#182]
I can't understand, my topic seems to have been added to the collection, but it's been a week and it's still not on the site. how often is your site updated?

**Comment by uPagge** [comment]
Hello?

**Comment by JugglerX** [comment]
@uPagge Hi, I've checked the theme and it has been disabled by the build script because the github url provided `github: 'https://github.com/uPagge/uBloggerr'` is not found.

Can you double check this url is correct and if not please do another PR updating the correct URL.

**Comment by uPagge** [comment]
Oh, I added an extra letter to our name.
