### ISSUE TITLE
I just can't find my theme

### ISSUE THREAD

**Issue by uPagge** [stackbithq/jamstackthemes#189]
It's been 6 days with PR, but I still can't find my theme in your directory :(

PR: https://github.com/stackbithq/jamstackthemes/pull/185

**Comment by JugglerX** [comment]
@uPagge I'm sorry about this. Not sure why it did not go live with the rebuild. I've investigated it and the theme is now live.

**Comment by uPagge** [comment]
Yes, I did. Thanks for the help))
