### ISSUE TITLE
Error Building Site

### ISSUE THREAD

**Issue by arhen** [stackbithq/jamstackthemes#33]
I got this error when trying to build site using 

`Hugo Serve`
------------------------------------
`Error: Error building site: failed to render pages: render of "home" failed: "C:\Users\Dell\Projects\jamstackthemes\themes\jamstackthemes\layouts\index.rss.xml:24:38": execute of template failed: template: index.rss.xml:24:38: executing "index.rss.xml" at <substr (replace .Params.github "/" "-") 19>: error calling substr: start position out of bounds for 0-byte string   `

**Comment by Jinksi** [comment]
Hey @arhen 
I had this issue as well, I _temporarily_ solved it by installing the version of Hugo specified in `netlify.toml`:
https://github.com/stackbithq/jamstackthemes/blob/0fbdcd73a885478ed2088e127d56190f83c97485/netlify.toml#L6
You can download it from the [Hugo releases page](https://github.com/gohugoio/hugo/releases).

**Comment by arhen** [comment]
Thank you @Jinksi for the answer. 
I have Hugo 0.59 on my machine. 
Is it possible to build it without downgrade?
