### ISSUE TITLE
Add ZEIT deploy buttons

### ISSUE THREAD

**Issue by rauchg** [stackbithq/jamstackthemes#61]
I'd love to work on a PR to make the themes deployable. Where do you think would be the best place?

Some ideas:

![image](https://user-images.githubusercontent.com/13041/72566764-40511a80-3869-11ea-8b62-20cc450535b7.png)

![image](https://user-images.githubusercontent.com/13041/72566786-4a731900-3869-11ea-8f55-caffe8d619cb.png)

I'd love to hear your thoughts!

**Comment by JugglerX** [comment]
Hi Guillermo, It's a good idea and one we have considered. So far we have been careful not to single out or promote a specific hosting/deployment method. We do not plan to add this feature just yet.

I appreciate you offer to help, and I'll ping you if/when we decide to pursue this.

**Comment by rauchg** [comment]
@JugglerX I could implement it as a `<dialog>` so we provide multiple deployment choices. What do you think?

**Comment by JugglerX** [comment]
The UI implementation is not the problem. We are not ready to add deployment buttons and "actions" beyond the regular category system we already have in place.

**Comment by rauchg** [comment]
@JugglerX see this tweet by @mgonto!

https://twitter.com/mgonto/status/1251231075801546752

Should we re-open this?
