### ISSUE TITLE
Add Netlify CMS Themes

### ISSUE THREAD

**Issue by slavakurilyak** [stackbithq/jamstackthemes#94]
The Netlify team maintains and updates a list of Netlify CMS templates ([website](https://templates.netlify.com/), [repo](https://github.com/netlify/templates)) which can be added to JAMstack Themes.

**Comment by JugglerX** [comment]
Yes it's a great resource. We'd need someone to add all those markdown files and clean up the front-matter.

**Comment by sharadcodes** [comment]
I can add and clean those, assign it to me

**Comment by JugglerX** [comment]
@sharadcodes thanks mate, that would be great! 

keep in mind, that some of those themes have probably already been added. So it would be best if you can check they exist first instead of adding duplicates.

**Comment by sharadcodes** [comment]
Alright, cool

**Comment by sharadcodes** [comment]
Check the PR I've added them

**Comment by sharadcodes** [comment]
Can't I add multiple themes at once ?

**Comment by JugglerX** [comment]
I've reviewed the PR

**Comment by sharadcodes** [comment]
> I've reviewed the PR

Fixed the issue @JugglerX
